### ISSUE TITLE
System to automate launches and check output

### ISSUE THREAD

**Issue by awesomebytes** [Robobench/robobench.experiments#1]
I've randomly found out this package and I've seen that it seems you configure (complicated) environments to be launched and to be evaluated for output with a .ini file. I'm very curious to know which system is actually parsing those .ini's and executing the stuff.

Is it some opensource tool? Do you know of any simulation-launching (ros friendly) environment like that? Did you build your own?

Thank you very much for your time :)

**Comment by jon-weisz** [comment]
The answer is yes - this package is based around citk, you can see how I use it with ROS here:

https://toolkit.cit-ec.uni-bielefeld.de/robobench/intro

The ICRA paper based on it was just accepted, and we used some of the REEM simulations I bothered you about 2 years ago.
